version: '3.8'

# Development override configuration
# Usage: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ../src:/app/src
      - ../config:/app/config
      - ../tests:/app/tests
    environment:
      - LOG_LEVEL=DEBUG
      - DEVELOPMENT=true

  streamlit:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    command: streamlit run src/ui/streamlit_dashboard.py --server.port 8501 --server.address 0.0.0.0 --server.runOnSave true
    volumes:
      - ../src:/app/src
      - ../config:/app/config
    environment:
      - STREAMLIT_DEVELOPMENT=true

  mcp-server:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    volumes:
      - ../src:/app/src
      - ../config:/app/config
    environment:
      - MCP_DEBUG=true

  worker:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    volumes:
      - ../src:/app/src
      - ../config:/app/config
    environment:
      - CELERY_TASK_ALWAYS_EAGER=false
      - LOG_LEVEL=DEBUG

  # Development tools
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: enhanced-agentic-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - agent-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: enhanced-agentic-redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - agent-network