# Prometheus configuration for monitoring Enhanced Agentic Workflow

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'enhanced-agentic-workflow'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load rules once and periodically evaluate them
rule_files:
  - "alerts.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # API service metrics
  - job_name: 'api'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Streamlit metrics (if exposed)
  - job_name: 'streamlit'
    static_configs:
      - targets: ['streamlit:8501']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # MCP server metrics
  - job_name: 'mcp-server'
    static_configs:
      - targets: ['mcp-server:8765']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Redis exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # PostgreSQL exporter (if added)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Node exporter for host metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # Celery metrics
  - job_name: 'celery'
    static_configs:
      - targets: ['worker:9540']
    metrics_path: '/metrics'
    scrape_interval: 30s